insert into houses (street, number, addition, zipCode, city, userID) values ('Mandrake', '47', 'A', '164903', 'Novodvinsk', 5);
insert into houses (street, number, addition, zipCode, city, userID) values ('Fordem', '28507', 'A', null, 'Seredyna-Buda', 5);
insert into houses (street, number, addition, zipCode, city, userID) values ('Red Cloud', '53', 'D', null, 'La’ershan', 5);
insert into houses (street, number, addition, zipCode, city, userID) values ('Bartillon', '09', 'D', '62-230', 'Witkowo', 5);
insert into houses (street, number, addition, zipCode, city, userID) values ('Farwell', '6851', 'D', null, 'Tukhlya', 2);
insert into houses (street, number, addition, zipCode, city, userID) values ('Arrowood', '1', 'B', '2113', 'Papakura', 2);
insert into houses (street, number, addition, zipCode, city, userID) values ('Thierer', '5', 'B', null, 'Chulakivka', 5);
insert into houses (street, number, addition, zipCode, city, userID) values ('Tomscot', '20410', 'B', null, 'Dongping', 1);
insert into houses (street, number, addition, zipCode, city, userID) values ('South', '87946', 'A', null, 'Curibaya', 34);
insert into houses (street, number, addition, zipCode, city, userID) values ('Stoughton', '5', 'E', null, 'Abéché', 5);
insert into houses (street, number, addition, zipCode, city, userID) values ('Center', '70611', 'E', '396458', 'Kamensk-Shakhtinskiy', 5);
insert into houses (street, number, addition, zipCode, city, userID) values ('Monterey', '718', 'D', null, 'Jidong', 34);
insert into houses (street, number, addition, zipCode, city, userID) values ('Porter', '81', 'B', '49980-000', 'Neópolis', 34);
insert into houses (street, number, addition, zipCode, city, userID) values ('Dottie', '58', 'A', null, 'Konza', 5);
insert into houses (street, number, addition, zipCode, city, userID) values ('Bluejay', '93446', 'A', null, 'Shantoudian', 5);
insert into houses (street, number, addition, zipCode, city, userID) values ('Buena Vista', '4734', 'E', '34-442', 'Łapsze Niżne', 34);
insert into houses (street, number, addition, zipCode, city, userID) values ('Almo', '346', 'B', null, 'Tirah', 2);
insert into houses (street, number, addition, zipCode, city, userID) values ('Oxford', '7380', 'E', '4116', 'Biñan', 34);
insert into houses (street, number, addition, zipCode, city, userID) values ('North', '4', 'B', '38009 CEDEX 1', 'Grenoble', 1);
insert into houses (street, number, addition, zipCode, city, userID) values ('Atwood', '9564', 'B', 'V6S', 'Fort Macleod', 1);
insert into houses (street, number, addition, zipCode, city, userID) values ('Mesta', '829', 'D', null, 'Zhenchuan', 2);
insert into houses (street, number, addition, zipCode, city, userID) values ('Sunnyside', '061', 'A', null, 'Wufu', 5);
insert into houses (street, number, addition, zipCode, city, userID) values ('Hanover', '15', 'A', '74982 CEDEX 9', 'Annecy', 2);
insert into houses (street, number, addition, zipCode, city, userID) values ('Hoffman', '728', 'C', '8193', 'Calvinia', 1);
insert into houses (street, number, addition, zipCode, city, userID) values ('Fordem', '17674', 'D', null, 'Dharān Bāzār', 1);
insert into houses (street, number, addition, zipCode, city, userID) values ('Talmadge', '59', 'C', '62280-000', 'Santa Quitéria', 34);
insert into houses (street, number, addition, zipCode, city, userID) values ('Forest Dale', '54', 'E', null, 'Karangtanjung', 5);
insert into houses (street, number, addition, zipCode, city, userID) values ('American', '2', 'D', '4111', 'Campana', 5);
insert into houses (street, number, addition, zipCode, city, userID) values ('Eagle Crest', '10', 'B', null, 'El Marañón', 1);
insert into houses (street, number, addition, zipCode, city, userID) values ('Toban', '92', 'B', null, 'Batang', 2);
insert into houses (street, number, addition, zipCode, city, userID) values ('Schurz', '981', 'B', '73-132', 'Suchań', 34);
insert into houses (street, number, addition, zipCode, city, userID) values ('Welch', '072', 'B', null, 'Koa', 2);
insert into houses (street, number, addition, zipCode, city, userID) values ('Bluejay', '582', 'D', null, 'Aelande', 1);
insert into houses (street, number, addition, zipCode, city, userID) values ('Miller', '45281', 'E', null, '‘Aqrah', 5);
insert into houses (street, number, addition, zipCode, city, userID) values ('Portage', '44347', 'E', null, 'Wafang', 34);
insert into houses (street, number, addition, zipCode, city, userID) values ('Lerdahl', '86', 'C', '111831', 'Bogotá', 34);
insert into houses (street, number, addition, zipCode, city, userID) values ('Meadow Valley', '7140', 'B', null, 'Luhans’ke', 5);
insert into houses (street, number, addition, zipCode, city, userID) values ('Manitowish', '35590', 'D', null, 'Mlonggo', 5);
insert into houses (street, number, addition, zipCode, city, userID) values ('Thierer', '41', 'C', '6004', 'Kecskemét', 5);
insert into houses (street, number, addition, zipCode, city, userID) values ('Manufacturers', '208', 'A', null, 'Aguasay', 1);
insert into houses (street, number, addition, zipCode, city, userID) values ('Prentice', '30445', 'D', null, 'Padangbatung', 1);
insert into houses (street, number, addition, zipCode, city, userID) values ('Jackson', '28745', 'C', '507 23', 'Zliv', 1);
insert into houses (street, number, addition, zipCode, city, userID) values ('Cody', '832', 'E', '457 23', 'Tanumshede', 1);
insert into houses (street, number, addition, zipCode, city, userID) values ('Fisk', '6451', 'A', null, 'Belmopan', 1);
insert into houses (street, number, addition, zipCode, city, userID) values ('Warner', '84', 'D', null, 'Hengjie', 2);
insert into houses (street, number, addition, zipCode, city, userID) values ('Westridge', '8641', 'D', null, 'Hanjiaji', 34);
insert into houses (street, number, addition, zipCode, city, userID) values ('Myrtle', '49677', 'D', null, 'Sovetakan', 1);
insert into houses (street, number, addition, zipCode, city, userID) values ('Butternut', '05492', 'D', null, 'Lincheng', 1);
insert into houses (street, number, addition, zipCode, city, userID) values ('Algoma', '7', 'A', '68540', 'San Miguel', 34);
insert into houses (street, number, addition, zipCode, city, userID) values ('6th', '44475', 'B', '2635-034', 'Rio de Mouro', 1);
insert into houses (street, number, addition, zipCode, city, userID) values ('Grover', '24', 'C', null, 'Yecun', 2);
insert into houses (street, number, addition, zipCode, city, userID) values ('Vernon', '0', 'B', '2005', 'Santa Teresa First', 5);
insert into houses (street, number, addition, zipCode, city, userID) values ('Nelson', '01', 'B', null, 'Huyang', 34);
insert into houses (street, number, addition, zipCode, city, userID) values ('Fulton', '711', 'B', null, 'Yangdenghu', 2);
insert into houses (street, number, addition, zipCode, city, userID) values ('Dexter', '8', 'B', '39605 CEDEX', 'Arbois', 1);
insert into houses (street, number, addition, zipCode, city, userID) values ('Sunbrook', '27', 'C', null, 'Stari Kuty', 5);
insert into houses (street, number, addition, zipCode, city, userID) values ('Granby', '65440', 'B', null, 'Baykonyr', 5);
insert into houses (street, number, addition, zipCode, city, userID) values ('Pond', '78', 'D', null, 'Zhentou', 34);
insert into houses (street, number, addition, zipCode, city, userID) values ('7th', '3', 'A', null, 'Xiapu', 1);
insert into houses (street, number, addition, zipCode, city, userID) values ('2nd', '38', 'E', '39630', 'Shahkot', 34);
insert into houses (street, number, addition, zipCode, city, userID) values ('Kenwood', '52', 'C', '60624', 'Chicago', 1);
insert into houses (street, number, addition, zipCode, city, userID) values ('Talisman', '760', 'B', '89-320', 'Wysoka', 1);
insert into houses (street, number, addition, zipCode, city, userID) values ('Harbort', '725', 'B', null, 'Yanxi', 1);
insert into houses (street, number, addition, zipCode, city, userID) values ('Petterle', '601', 'E', '547079', 'El Carmen', 34);
insert into houses (street, number, addition, zipCode, city, userID) values ('Shoshone', '02156', 'B', null, 'El Corozo', 2);
insert into houses (street, number, addition, zipCode, city, userID) values ('Mayer', '36535', 'C', null, 'Yangambi', 2);
insert into houses (street, number, addition, zipCode, city, userID) values ('Debra', '895', 'D', '4427', 'Siruma', 34);
insert into houses (street, number, addition, zipCode, city, userID) values ('Fairfield', '8', 'C', '00174', 'Roma', 34);
insert into houses (street, number, addition, zipCode, city, userID) values ('Rutledge', '2028', 'A', '18530-000', 'Tietê', 1);
insert into houses (street, number, addition, zipCode, city, userID) values ('Dunning', '785', 'E', '09-120', 'Nowe Miasto', 1);
insert into houses (street, number, addition, zipCode, city, userID) values ('Clarendon', '1207', 'B', null, 'Polel Diaoubé', 2);
insert into houses (street, number, addition, zipCode, city, userID) values ('Artisan', '75', 'D', null, 'Changjiangbu', 5);
insert into houses (street, number, addition, zipCode, city, userID) values ('Service', '03848', 'D', '93704', 'Fresno', 2);
insert into houses (street, number, addition, zipCode, city, userID) values ('Gulseth', '629', 'B', '34-115', 'Ryczów', 2);
insert into houses (street, number, addition, zipCode, city, userID) values ('Prairie Rose', '23536', 'E', '6405', 'Allen', 5);
insert into houses (street, number, addition, zipCode, city, userID) values ('Manley', '580', 'E', '59-402', 'Jawor', 2);
insert into houses (street, number, addition, zipCode, city, userID) values ('Del Sol', '01', 'B', null, 'Waepau', 1);
insert into houses (street, number, addition, zipCode, city, userID) values ('Homewood', '63', 'C', null, 'Acas', 1);
insert into houses (street, number, addition, zipCode, city, userID) values ('Meadow Ridge', '139', 'C', null, 'Yanqul', 1);
insert into houses (street, number, addition, zipCode, city, userID) values ('Hanover', '0064', 'B', null, 'Pancalan', 2);
insert into houses (street, number, addition, zipCode, city, userID) values ('Bultman', '1846', 'E', '531 36', 'Lidköping', 2);
insert into houses (street, number, addition, zipCode, city, userID) values ('Londonderry', '85', 'C', null, 'Xinyu', 34);
insert into houses (street, number, addition, zipCode, city, userID) values ('Surrey', '97', 'B', null, 'Hongqiao', 1);
insert into houses (street, number, addition, zipCode, city, userID) values ('Fuller', '2', 'B', '8310', 'Dinaig', 2);
insert into houses (street, number, addition, zipCode, city, userID) values ('Elmside', '2', 'B', '26-050', 'Kaniów', 5);
insert into houses (street, number, addition, zipCode, city, userID) values ('Red Cloud', '96', 'B', '347513', 'Orlovskiy', 34);
insert into houses (street, number, addition, zipCode, city, userID) values ('Logan', '78979', 'B', '4274', 'Žirovnica', 34);
insert into houses (street, number, addition, zipCode, city, userID) values ('Loeprich', '28614', 'D', null, 'Thị Trấn Phước Bửu', 2);
insert into houses (street, number, addition, zipCode, city, userID) values ('Bonner', '04', 'D', null, 'Hongshan', 2);
insert into houses (street, number, addition, zipCode, city, userID) values ('Merchant', '566', 'A', null, 'Geghanist', 5);
insert into houses (street, number, addition, zipCode, city, userID) values ('Melvin', '53658', 'E', '8300', 'Neuquén', 2);
insert into houses (street, number, addition, zipCode, city, userID) values ('Vernon', '22348', 'D', null, 'Al Tuḩaytā’', 34);
insert into houses (street, number, addition, zipCode, city, userID) values ('Kensington', '5388', 'A', '44315', 'Akron', 2);
insert into houses (street, number, addition, zipCode, city, userID) values ('Ilene', '8', 'D', '55-093', 'Kiełczów', 5);
insert into houses (street, number, addition, zipCode, city, userID) values ('Burrows', '3588', 'E', null, 'Xinwan', 34);
insert into houses (street, number, addition, zipCode, city, userID) values ('Donald', '663', 'B', null, 'Sangba', 2);
insert into houses (street, number, addition, zipCode, city, userID) values ('Clemons', '7317', 'C', null, 'Birātnagar', 2);
insert into houses (street, number, addition, zipCode, city, userID) values ('Dixon', '716', 'B', 'L6J', 'Oakville', 2);
insert into houses (street, number, addition, zipCode, city, userID) values ('Park Meadow', '401', 'D', '78325-000', 'Aripuanã', 34);
insert into houses (street, number, addition, zipCode, city, userID) values ('Cardinal', '14', 'D', '899-8607', 'Sueyoshichō-ninokata', 34);
insert into houses (street, number, addition, zipCode, city, userID) values ('Kensington', '032', 'B', null, 'Chongjin', 34);
insert into houses (street, number, addition, zipCode, city, userID) values ('Melody', '4956', 'D', null, 'Tangkolo', 1);
insert into houses (street, number, addition, zipCode, city, userID) values ('Petterle', '933', 'D', 'J6V', 'Charlemagne', 34);
insert into houses (street, number, addition, zipCode, city, userID) values ('Waywood', '0', 'C', null, 'Hīsh', 5);
insert into houses (street, number, addition, zipCode, city, userID) values ('Corry', '51', 'B', '43-354', 'Roczyny', 1);
insert into houses (street, number, addition, zipCode, city, userID) values ('Bonner', '66313', 'B', null, 'Dongyangzhen', 1);
insert into houses (street, number, addition, zipCode, city, userID) values ('Spohn', '2', 'C', '86360-000', 'Bandeirantes', 5);
insert into houses (street, number, addition, zipCode, city, userID) values ('Center', '93', 'C', null, 'Baishui', 5);
insert into houses (street, number, addition, zipCode, city, userID) values ('Lindbergh', '9001', 'D', '7406', 'General La Madrid', 1);
insert into houses (street, number, addition, zipCode, city, userID) values ('Southridge', '9', 'E', null, 'Watulumbung', 1);
insert into houses (street, number, addition, zipCode, city, userID) values ('Redwing', '08086', 'D', null, 'Dainan', 34);
insert into houses (street, number, addition, zipCode, city, userID) values ('Fulton', '0', 'E', null, 'Bajingzi', 1);
insert into houses (street, number, addition, zipCode, city, userID) values ('Buell', '1', 'A', '8601', 'Buenavista', 5);
insert into houses (street, number, addition, zipCode, city, userID) values ('Bay', '0978', 'D', '257 44', 'Netvořice', 34);
insert into houses (street, number, addition, zipCode, city, userID) values ('Forest Run', '9', 'E', '54000-000', 'Jaboatão dos Guararapes', 1);
insert into houses (street, number, addition, zipCode, city, userID) values ('Hallows', '2216', 'E', null, 'Lewokluok', 34);
insert into houses (street, number, addition, zipCode, city, userID) values ('Meadow Valley', '7', 'E', null, 'Kebonan', 34);
insert into houses (street, number, addition, zipCode, city, userID) values ('Thompson', '4277', 'D', null, 'Shchastya', 5);
insert into houses (street, number, addition, zipCode, city, userID) values ('Hazelcrest', '31', 'B', '1004', 'Amsterdam', 5);
insert into houses (street, number, addition, zipCode, city, userID) values ('Fordem', '655', 'C', null, 'Chaoyang', 1);
insert into houses (street, number, addition, zipCode, city, userID) values ('Mitchell', '23', 'A', '25705', 'Huntington', 34);
insert into houses (street, number, addition, zipCode, city, userID) values ('Del Sol', '1451', 'B', null, 'Chelu', 2);
insert into houses (street, number, addition, zipCode, city, userID) values ('Almo', '0217', 'C', '618283', 'Shumikhinskiy', 1);
insert into houses (street, number, addition, zipCode, city, userID) values ('Waxwing', '8387', 'C', '33405', 'West Palm Beach', 1);
insert into houses (street, number, addition, zipCode, city, userID) values ('Hallows', '37', 'A', null, 'Kalimeneng', 2);
insert into houses (street, number, addition, zipCode, city, userID) values ('Garrison', '133', 'A', null, 'Al Finţās', 34);
insert into houses (street, number, addition, zipCode, city, userID) values ('Anzinger', '273', 'A', null, 'Darmasari', 1);
insert into houses (street, number, addition, zipCode, city, userID) values ('Butternut', '4079', 'E', '88350-000', 'Brusque', 1);
insert into houses (street, number, addition, zipCode, city, userID) values ('Utah', '292', 'A', '5001', 'Cadagmayan Norte', 34);
insert into houses (street, number, addition, zipCode, city, userID) values ('Kensington', '68', 'A', '3180', 'Federal', 2);
insert into houses (street, number, addition, zipCode, city, userID) values ('Eagan', '319', 'A', null, 'Yongshan', 34);
insert into houses (street, number, addition, zipCode, city, userID) values ('Evergreen', '51999', 'C', '452941', 'Agidel’', 34);
insert into houses (street, number, addition, zipCode, city, userID) values ('Grim', '3779', 'B', '2530-327', 'Zambujeira', 1);
insert into houses (street, number, addition, zipCode, city, userID) values ('Milwaukee', '7', 'A', null, 'Llauta', 2);
insert into houses (street, number, addition, zipCode, city, userID) values ('Golf View', '1', 'E', null, 'Zouiat ech Cheïkh', 5);
insert into houses (street, number, addition, zipCode, city, userID) values ('Calypso', '1', 'C', null, 'Zhuyu', 2);
insert into houses (street, number, addition, zipCode, city, userID) values ('Roth', '84536', 'C', null, 'Datangzhuang', 5);
insert into houses (street, number, addition, zipCode, city, userID) values ('Ramsey', '823', 'E', null, 'Chongjin', 34);
insert into houses (street, number, addition, zipCode, city, userID) values ('Goodland', '5', 'B', '27600-000', 'Valença', 5);
insert into houses (street, number, addition, zipCode, city, userID) values ('Bayside', '8', 'C', '87900', 'Kajaani', 2);
insert into houses (street, number, addition, zipCode, city, userID) values ('Jay', '38', 'C', '3850-312', 'Alquerubim', 1);
insert into houses (street, number, addition, zipCode, city, userID) values ('Sundown', '1563', 'E', null, 'Torbat-e Jām', 2);
insert into houses (street, number, addition, zipCode, city, userID) values ('Dapin', '64646', 'E', null, 'Zhulin', 34);
insert into houses (street, number, addition, zipCode, city, userID) values ('David', '10957', 'A', null, 'Mungui', 5);
insert into houses (street, number, addition, zipCode, city, userID) values ('Delaware', '407', 'B', '99000-000', 'Passo Fundo', 34);
insert into houses (street, number, addition, zipCode, city, userID) values ('Monument', '850', 'C', null, 'Ntoum', 2);
insert into houses (street, number, addition, zipCode, city, userID) values ('Pennsylvania', '11', 'A', null, 'Mişrātah', 2);
insert into houses (street, number, addition, zipCode, city, userID) values ('Glendale', '2493', 'A', null, 'Xinhua', 1);
insert into houses (street, number, addition, zipCode, city, userID) values ('Victoria', '716', 'C', null, 'Bichena', 5);
insert into houses (street, number, addition, zipCode, city, userID) values ('Sloan', '7', 'E', '135 22', 'Tyresö', 2);
